import Head from 'next/head';
import Image from 'next/image';
import styles from '../../styles/Home.module.css';
import { PeopleData, getPeoplesInfo } from '../api/peoples';
import GeneratePDF from '../../components/GeneratePDF';

export default function Home(props: { peoples: PeopleData[] }) {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>Next.js Convert HTML Table To PDF</h1>
        <div>
          <ul>
            {props.peoples.map(({ name }, i) => (
              <li key={i}>{name}</li>
            ))}
          </ul>
        </div>
        <GeneratePDF person={props.peoples}></GeneratePDF>
      </main>
    </div>
  );
}

export async function getStaticProps() {
  const peoples: PeopleData[] = await getPeoplesInfo();
  return {
    props: {
      peoples,
    },
  };
}
