import { use } from 'react';
import Head from 'next/head';
import Image from 'next/image';
import styles from '../../styles/Home.module.css';
import { PeopleData, getPeoplesInfo } from '../api/peoples';
import GeneratePDF from '../../components/GeneratePDF';
import { getProductList, ProductItem } from '../api/productList';
import ProductListTemplate from '../../components/PDFTemplate/productListTemplate';
import { downloadPDF } from '../../components/downloadPDF';

export default function Home(props: { peoples: PeopleData[]; productList: ProductItem[] }) {
  return (
    <>
      <div>
        <ProductListTemplate productList={props.productList}></ProductListTemplate>
        <button type="button" onClick={downloadPDF}>
          downloadPDF
        </button>
      </div>
      <div className={styles.container}>
        <Head>
          <title>Create Next App</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>

        <main className={styles.main}>
          <h1 className={styles.title}>Next.js Convert HTML Table To PDF</h1>
          <div>
            <ul>
              {props.peoples.map(({ name }, i) => (
                <li key={i}>{name}</li>
              ))}
            </ul>
          </div>
          <div id="content">
            <h3>HTML in page</h3>
            <h4>a</h4>
            <table id="tab_customers" className="table table-striped">
              <thead>
                <tr className="warning">
                  <th>Project Name</th>
                  <th>Start Date</th>
                  <th>End Date</th>
                  <th>Last Updated</th>
                </tr>
              </thead>
              <tbody>
                <tr>
                  <td>NM Connect - NMETNMCM</td>
                  <td>Dec 13, 2017</td>
                  <td>Jan 1, 2018</td>
                  <td>Dec 13, 2017</td>
                </tr>
              </tbody>
            </table>
            <p>abcdefg</p>
          </div>
          <GeneratePDF person={props.peoples}></GeneratePDF>
        </main>
      </div>
    </>
  );
}

export async function getStaticProps() {
  const peoples: PeopleData[] = await getPeoplesInfo();
  const productList: ProductItem[] = await getProductList();
  return {
    props: {
      peoples,
      productList,
    },
  };
}
