import { use } from 'react';
import Head from 'next/head';
import Image from 'next/image';
import styles from '../../styles/Home.module.css';
import { PeopleData, getPeoplesInfo } from '../api/peoples';
import GeneratePDF from '../../components/GeneratePDF';

export default function Home(props: { peoples: PeopleData[] }) {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>Next.js Convert HTML Table To PDF</h1>
        <div>
          <ul>
            {props.peoples.map(({ name }, i) => (
              <li key={i}>{name}</li>
            ))}
          </ul>
        </div>
        <div id="content">
          <h3>Time & Materials Statement of Work (SOW)</h3>
          <h4>General Information</h4>
          <table id="tab_customers" className="table table-striped">
            <colgroup>
              <col span="1" />
              <col span="1" />
            </colgroup>
            <thead>
              <tr className="warning">
                <th>SOW Creation Date</th>
                <th>SOW Start Date</th>
                <th>Project</th>
                <th>Last Updated</th>
                <th>SOW End Date</th>
              </tr>
            </thead>
            <tbody>
              <tr>
                <td>Dec 13, 2017</td>
                <td>Jan 1, 2018</td>
                <td>NM Connect - NMETNMCM</td>
                <td>Dec 13, 2017</td>
                <td>Dec 31, 2018</td>
              </tr>
            </tbody>
          </table>
          <p>
            This is a Time and Materials Statement of Work between Northwestern Mutual Life Insurance Company and
            Infosys with all general terms and conditions as described in the current Master Agreement and its related
            documents
          </p>
        </div>
        <GeneratePDF person={props.peoples}></GeneratePDF>
      </main>
    </div>
  );
}

export async function getStaticProps() {
  const peoples: PeopleData[] = await getPeoplesInfo();
  return {
    props: {
      peoples,
    },
  };
}
